# ! these configuration are meant for development purposes only, please do not use these in production environment

environment = "development"

# ** main app
[app]
address = "127.0.0.1:8000"

is_frontend_separately_hosted = false

encryption_key = "0123456789abcdef0123456789abcdef"

# this flag to be true if in case you want to host the frontend separately from the backend,
# like on vercel, so enabling this flag would skip on building and bundling of the frontend 
# with the fo executable
IS_SELF_HOSTED = true

# default user details
default_user_email = "dev@wapikit.com"
default_user_password = "dev@wapikit.com"
default_user_username = "devuser"
default_user_name = "Developer"
jwt_secret = "wdliahdsoihodjpkpeohifghqoew86e981u2ihn"

# redis
[redis]
url = "redis://localhost:6379"


# Database configuration
[database]
url = "postgres://wapikit-dev:wapikit-dev@database:5432/wapikit-dev?sslmode=disable"


[slack]
webhook_url = ""
channel = ""

[email]
host = ""
port = 587
username = ""
password = ""
