version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - wapikit-dev
    environment:
      - POSTGRES_PASSWORD=wapikit-dev
      - POSTGRES_USER=wapikit-dev
      - POSTGRES_DB=wapikit-dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: wapikit-dev-db
        target: /var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - wapikit-dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: wapikit-dev-redis
        target: /data

volumes:
  wapikit-dev-db:
  wapikit-dev-redis:

networks:
  wapikit-dev:
