name: Production Documentation Build

on:
  push:
    branches:
      - disabled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-swagger-config:
    name: Build & upload documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout docs repository
        uses: actions/checkout@v3
        with:
          repository: "sarthakjdev/wapikit.com"
          token: ${{ secrets.WAPIJS_DOCS_ACCESS_TOKEN }}
          path: "out"

      - name: Move collections file to correct directory
        run: |
          mv "swagger/collections.yaml" "out/collections.yaml"

      - name: Commit and push
        run: |
          cd out
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Docs build for ${GITHUB_REF_TYPE} ${GITHUB_REF_NAME}: ${GITHUB_SHA}" || true
          git push
